title: Monteer een draad aan een enkele knop
hero_image: images/banner.png
description: Hoe een enkele knop op een Raspberry Pi Pico aan te sluiten
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - 
    title: Monteer een draad aan een enkele knop
