title: Wiring a single button
hero_image: images/banner.png
description: single-button-wiring description
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
