title: Wire a single button
hero_image: images/banner.png
description: How to wire a single button to a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - 
    title: Wire a single button
