---
title: Câbler un seul bouton
hero_image: images/banner.png
description: Comment câbler un seul bouton à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-10"
steps:
  - title: Câbler un seul bouton
